---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: brianbyers/concourse-gradle
    tag: "latest"

inputs:
  - name: git-repo

caches:
  - path: git-repo/.mvn

run:
  path: git-repo/ci/scripts/unit.sh
